/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Executive;

import javax.swing.JOptionPane;

/**
 *
 * @author parma
 */
public class Group_Details extends javax.swing.JFrame {

    /**
     * Creates new form Group_Details
     */
    public Group_Details() {
        initComponents();
        change();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jb25p = new javax.swing.JRadioButton();
        jb50p = new javax.swing.JRadioButton();
        jb75p = new javax.swing.JRadioButton();
        jb100p = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        d25p = new javax.swing.JRadioButton();
        d50p = new javax.swing.JRadioButton();
        d75p = new javax.swing.JRadioButton();
        d100p = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pdesc = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        g25p = new javax.swing.JRadioButton();
        g50p = new javax.swing.JRadioButton();
        g75p = new javax.swing.JRadioButton();
        g100p = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(370, 10, 100, 30);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(500, 10, 100, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setText("-");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(80, 320, 10, 29);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setText("-");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(80, 270, 20, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("-");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(80, 230, 20, 20);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        buttonGroup3.add(jb25p);
        jb25p.setText("0-25%");
        jb25p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb25pActionPerformed(evt);
            }
        });

        buttonGroup3.add(jb50p);
        jb50p.setText("25-50%");
        jb50p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb50pActionPerformed(evt);
            }
        });

        buttonGroup3.add(jb75p);
        jb75p.setText("50-75%");
        jb75p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb75pActionPerformed(evt);
            }
        });

        buttonGroup3.add(jb100p);
        jb100p.setText("75-100%");
        jb100p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb100pActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jb25p)
                .addGap(45, 45, 45)
                .addComponent(jb50p)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jb75p)
                .addGap(44, 44, 44)
                .addComponent(jb100p)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb25p)
                    .addComponent(jb50p)
                    .addComponent(jb75p)
                    .addComponent(jb100p))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(190, 320, 410, 40);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        buttonGroup2.add(d25p);
        d25p.setText("0-25%");
        d25p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d25pActionPerformed(evt);
            }
        });

        buttonGroup2.add(d50p);
        d50p.setText("25-50%");
        d50p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d50pActionPerformed(evt);
            }
        });

        buttonGroup2.add(d75p);
        d75p.setText("50-75%");
        d75p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d75pActionPerformed(evt);
            }
        });

        buttonGroup2.add(d100p);
        d100p.setText("75-100%");
        d100p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                d100pActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(d25p, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(d50p, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(d75p, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(d100p)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(d50p)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(d25p)
                        .addComponent(d75p)
                        .addComponent(d100p)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(190, 270, 410, 40);

        pdesc.setColumns(20);
        pdesc.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        pdesc.setRows(5);
        pdesc.setText(" This project is about the railway management system that will deal with the management\n of rail network. This will deal with the scheduling of the trains and the bogey and engine\n maintainence. The main advantage is that the ticket booking will be online and the other \n hassles will be avoided.");
        pdesc.setBorder(null);
        jScrollPane1.setViewportView(pdesc);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(60, 120, 540, 60);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextField1.setText("Railway Management System");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jTextField1);
        jTextField1.setBounds(60, 60, 540, 30);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        buttonGroup1.add(g25p);
        g25p.setText("0-25%");
        g25p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g25pActionPerformed(evt);
            }
        });

        buttonGroup1.add(g50p);
        g50p.setText("25-50%");
        g50p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g50pActionPerformed(evt);
            }
        });

        buttonGroup1.add(g75p);
        g75p.setText("50-75%");
        g75p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g75pActionPerformed(evt);
            }
        });

        buttonGroup1.add(g100p);
        g100p.setText("75-100%");
        g100p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                g100pActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(g25p, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(g50p, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(g75p, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(g100p)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(g25p)
                    .addComponent(g50p)
                    .addComponent(g75p)
                    .addComponent(g100p))
                .addGap(45, 45, 45))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(190, 220, 410, 40);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Java Beans");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 330, 70, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Database");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 280, 60, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("GUI");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(100, 230, 70, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Project_Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(60, 30, 130, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Project_Description");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 90, 160, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Status");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 190, 100, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Executive/bgimg3.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void g50pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g50pActionPerformed
        // TODO add your handling code here:
        
        g25 = 50;
        
    }//GEN-LAST:event_g50pActionPerformed

    private void d75pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d75pActionPerformed
        // TODO add your handling code here:
        
        d25 = 75;
    }//GEN-LAST:event_d75pActionPerformed

    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        Student_Page sp = new Student_Page();
        sp.setVisible(true);
        sp.chat();
        sp.remarks();
        
    }//GEN-LAST:event_jButton1ActionPerformed
    public static String st;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
       
        st = pdesc.getText();
        Project_Details1.count=1;
        change();
        JOptionPane.showMessageDialog(null ,"The PROJECT INFORMATION has been SUBMITTED.");
    }//GEN-LAST:event_jButton2ActionPerformed

    public void change()
    {
        if(Project_Details1.count ==1)
        {
            pdesc.setText(st);
        }
    }
    public static int g25;
    private void g25pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g25pActionPerformed
        // TODO add your handling code here:
        
        g25 = 25;
       
    }//GEN-LAST:event_g25pActionPerformed

    
    private void g75pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g75pActionPerformed
        // TODO add your handling code here:
        
        g25 = 75;
    }//GEN-LAST:event_g75pActionPerformed

  
    private void g100pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_g100pActionPerformed
        // TODO add your handling code here:
        
        g25 = 100;
    }//GEN-LAST:event_g100pActionPerformed

    public static int d25;
    private void d25pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d25pActionPerformed
        // TODO add your handling code here:
        
        d25 = 25;
    }//GEN-LAST:event_d25pActionPerformed

    public static int jb25;
    private void jb25pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb25pActionPerformed
        // TODO add your handling code here:
        
        jb25 = 25;
    }//GEN-LAST:event_jb25pActionPerformed

    private void jb50pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb50pActionPerformed
        // TODO add your handling code here:
        
        jb25 = 50;
    }//GEN-LAST:event_jb50pActionPerformed

    private void jb75pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb75pActionPerformed
        // TODO add your handling code here:
        
        jb25 = 75;
    }//GEN-LAST:event_jb75pActionPerformed

    private void jb100pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb100pActionPerformed
        // TODO add your handling code here:
        
        jb25 = 100;
    }//GEN-LAST:event_jb100pActionPerformed

    private void d50pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d50pActionPerformed
        // TODO add your handling code here:
        
        d25 = 50;
    }//GEN-LAST:event_d50pActionPerformed

    private void d100pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_d100pActionPerformed
        // TODO add your handling code here:
        
        d25 = 100;
    }//GEN-LAST:event_d100pActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Group_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Group_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Group_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Group_Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Group_Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton d100p;
    private javax.swing.JRadioButton d25p;
    private javax.swing.JRadioButton d50p;
    private javax.swing.JRadioButton d75p;
    private javax.swing.JRadioButton g100p;
    private javax.swing.JRadioButton g25p;
    private javax.swing.JRadioButton g50p;
    private javax.swing.JRadioButton g75p;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton jb100p;
    private javax.swing.JRadioButton jb25p;
    private javax.swing.JRadioButton jb50p;
    private javax.swing.JRadioButton jb75p;
    public static javax.swing.JTextArea pdesc;
    // End of variables declaration//GEN-END:variables
}
