/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Executive;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.util.Stack;
import javax.swing.JOptionPane;

/**
 *
 * @author parma
 */
public class Project_Details1 extends javax.swing.JFrame {

    /**
     * Creates new form Project_Details1
     */
    public Project_Details1() {
        initComponents();
        change();
    }
    public static int count = 0;

    public void change() {
        if (count != 0) {
            prod.setText(Group_Details.st);
            Multithread1 mt1 = new Multithread1();
            Multithread2 mt2 = new Multithread2();
            Multithread3 mt3 = new Multithread3();
            mt1.start();
            mt2.start();
            mt3.start();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        prod = new javax.swing.JTextArea();
        jbprog = new javax.swing.JProgressBar();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        gprog = new javax.swing.JProgressBar();
        dprog = new javax.swing.JProgressBar();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Remark = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(520, 290, 100, 40);

        prod.setEditable(false);
        prod.setColumns(20);
        prod.setRows(5);
        prod.setText(" This project is about the railway management system that will deal with the management\n of rail network. This will deal with the scheduling of the trains and the bogey and engine\n maintainence. The main advantage is that the ticket booking will be online and the other \n hassles will be avoided.");
        jScrollPane1.setViewportView(prod);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(430, 60, 200, 160);

        jbprog.setToolTipText("");
        jbprog.setValue(75);
        jbprog.setStringPainted(true);
        jPanel1.add(jbprog);
        jbprog.setBounds(150, 190, 200, 20);

        jLabel7.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel7.setText("Java Beans ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 190, 140, 22);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(400, 10, 2, 230);

        gprog.setBackground(new java.awt.Color(0, 0, 0));
        gprog.setForeground(new java.awt.Color(0, 0, 0));
        gprog.setValue(40);
        gprog.setStringPainted(true);
        jPanel1.add(gprog);
        gprog.setBounds(150, 90, 200, 20);

        dprog.setToolTipText("");
        dprog.setValue(60);
        dprog.setStringPainted(true);
        jPanel1.add(dprog);
        dprog.setBounds(150, 140, 200, 20);

        jLabel9.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel9.setText("GUI ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 90, 70, 20);

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel10.setText("Database ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 140, 130, 22);

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel6.setText("Status ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(170, 20, 140, 30);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 20)); // NOI18N
        jLabel4.setText("Project Description ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(420, 20, 200, 25);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 340, 80, 30);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(50, 250, 550, 10);
        jPanel1.add(Remark);
        Remark.setBounds(50, 290, 450, 40);

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel2.setText("Remarks :-");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 260, 110, 22);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Executive/bgimg3.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 380);

        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 40, 200, 180);

        jLabel11.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel11.setText("Database :");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 140, 130, 29);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        Visit1 v2 = new Visit1();
        v2.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    public static String sremark;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        sremark = Remark.getText();
        if (sremark.length() == 0) {
            JOptionPane.showMessageDialog(null, "Please enter a remark.");
        } else {
            try {
                Class.forName("com.mysql.jdbc.Driver");
            } catch (ClassNotFoundException ex) {
                System.out.println("Error in JDBC");
            }
            try {
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project?verifyServerCertificate=false&useSSL=true", "root", "rishab");
                PreparedStatement p = con.prepareStatement("insert into remarks (col) value (?)");
                p.setString(1, sremark);
                p.execute();
                JOptionPane.showMessageDialog(null, "Remark has been submitted.");
            } catch (SQLException e) {
                System.err.println("Error.");
            }
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Project_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Project_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Project_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Project_Details1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Project_Details1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Remark;
    public static javax.swing.JProgressBar dprog;
    public static javax.swing.JProgressBar gprog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JProgressBar jbprog;
    private javax.swing.JTextArea prod;
    // End of variables declaration//GEN-END:variables
}

class Multithread1 extends Thread {

    public void run() {

        for (int i = 1; i <= Group_Details.g25; i++) {

            Project_Details1.gprog.setValue(i);
            try {
                Thread.sleep(7);
            } catch (InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

        }

    }
}

class Multithread2 extends Thread {

    public void run() {

        for (int i = 1; i <= Group_Details.d25; i++) {

            Project_Details1.dprog.setValue(i);
            try {
                Thread.sleep(7);
            } catch (InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

        }

    }
}

class Multithread3 extends Thread {

    public void run() {
        for (int i = 1; i <= Group_Details.jb25; i++) {

            Project_Details1.jbprog.setValue(i);
            try {
                Thread.sleep(7);
            } catch (InterruptedException e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }

        }

    }
}
