/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Executive;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author parma
 */
public class Update_Student_Profile extends javax.swing.JFrame {

    /**
     * Creates new form Update_Student_Profile
     */
    public Update_Student_Profile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        co = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        u = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(530, 30, 90, 31);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(120, 270, 400, 20);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update Info.");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(270, 300, 150, 31);
        jPanel1.add(co);
        co.setBounds(310, 230, 190, 30);
        jPanel1.add(c);
        c.setBounds(310, 180, 190, 30);
        jPanel1.add(u);
        u.setBounds(310, 130, 190, 30);
        jPanel1.add(n);
        n.setBounds(310, 80, 190, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Contact No.");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 230, 95, 22);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Class & Section");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 180, 123, 22);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("University Roll No.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 130, 150, 22);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 90, 60, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Executive/bgimg3.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        setVisible(false);
        Student_Profile sp = new Student_Profile();
        sp.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public static String uname;
    public static String unrn;
    public static String ucs;
    public static String ucn;

    public void change() {

        uname = n.getText();
        unrn = u.getText();
        ucs = c.getText();
        ucn = co.getText();
        if (uname.equalsIgnoreCase("") && unrn.equalsIgnoreCase("") && ucs.equalsIgnoreCase("") && ucn.equalsIgnoreCase("")) {
                JOptionPane.showMessageDialog(null, "Enter a field to update.");
        } else {
            
            JOptionPane.showMessageDialog(null ,"Your INFORMATION has been UPDATED.");
            setvaluestodb(uname, unrn, ucs, ucn);
        }
    }

    public void setvaluestodb(String u1name, String u1nrn, String u1cs, String u1cn) {
        try {
            System.out.println("String is: " + u1name);
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/project?verifyServerCertificate=false&useSSL=true", "root", "rishab");
            PreparedStatement p = con.prepareStatement("update student set   name=? ,uniroll=? ,cls=? , contact=? where username=?");
            p.setString(5, Student_Login.user);
            if (u1name.length() != 0) {
                p.setString(1, u1name);
               // Student_Profile.cname.setText(Student_Login.name);
                Student_Profile.cname.setText(uname);
                Student_Login.name = uname;
            } else {
                p.setString(1, Student_Login.name);
            }
            if (u1nrn.length() != 0) {
                p.setString(2, u1nrn);
                Student_Profile.cuniroll.setText(Student_Login.uni);
                Student_Profile.cuniroll.setText(unrn);
                Student_Login.uni = unrn;
            } else {
                p.setString(2, Student_Login.uni);

            }
            if (u1cs.length() != 0) {
                p.setString(3, u1cs);
                Student_Profile.ccls.setText(Student_Login.cs);
                Student_Profile.ccls.setText(ucs);
                Student_Login.cs = ucs;
            } else {
                p.setString(3, Student_Login.cs);

            }
            if (u1cn.length() != 0) {
                p.setString(4, u1cn);
                Student_Profile.ccon.setText(Student_Login.cn);
                Student_Profile.ccon.setText(ucn);
                Student_Login.cn = ucn;
            } else {
                p.setString(4, Student_Login.cn);

            }
            p.executeUpdate();
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(Update_Student_Profile.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        change();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Student_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Student_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Student_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Student_Profile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Student_Profile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c;
    private javax.swing.JTextField co;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField n;
    private javax.swing.JTextField u;
    // End of variables declaration//GEN-END:variables
}
